flist = [
    {"channel": "s", "mMediator": 200, "mDark": 1},
    {"channel": "s", "mMediator": 200, "mDark": 5},
    {"channel": "s", "mMediator": 200, "mDark": 10},
    {"channel": "s", "mMediator": 250, "mDark": 1},
    {"channel": "s", "mMediator": 250, "mDark": 5},
    {"channel": "s", "mMediator": 250, "mDark": 10},
    {"channel": "s", "mMediator": 300, "mDark": 1},
    {"channel": "s", "mMediator": 300, "mDark": 5},
    {"channel": "s", "mMediator": 300, "mDark": 10},
    {"channel": "s", "mMediator": 350, "mDark": 1},
    {"channel": "s", "mMediator": 350, "mDark": 5},
    {"channel": "s", "mMediator": 350, "mDark": 10},
    {"channel": "s", "mMediator": 400, "mDark": 1},
    {"channel": "s", "mMediator": 400, "mDark": 5},
    {"channel": "s", "mMediator": 400, "mDark": 10},
    {"channel": "s", "mMediator": 450, "mDark": 1},
    {"channel": "s", "mMediator": 450, "mDark": 5},
    {"channel": "s", "mMediator": 450, "mDark": 10},
    {"channel": "s", "mMediator": 500, "mDark": 1},
    {"channel": "s", "mMediator": 500, "mDark": 5},
    {"channel": "s", "mMediator": 500, "mDark": 10},
    {"channel": "s", "mMediator": 550, "mDark": 1},
    {"channel": "s", "mMediator": 550, "mDark": 5},
    {"channel": "s", "mMediator": 550, "mDark": 10},
]